// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8HMNFKnEv7gJ55SbTqvTiU
// Component: u1HD2iJpzl
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_im_xbeanies.module.css"; // plasmic-import: 8HMNFKnEv7gJ55SbTqvTiU/projectcss
import sty from "./PlasmicTestBttn.module.css"; // plasmic-import: u1HD2iJpzl/css

export const PlasmicTestBttn__VariantProps = new Array();

export const PlasmicTestBttn__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTestBttn__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <button
      data-plasmic-name={"testBttn"}
      data-plasmic-override={overrides.testBttn}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.testBttn
      )}
      ref={ref => {
        $refs["testBttn"] = ref;
      }}
    >
      {"Click Me"}
    </button>
  );
}

const PlasmicDescendants = {
  testBttn: ["testBttn"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTestBttn__ArgProps,
          internalVariantPropNames: PlasmicTestBttn__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTestBttn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "testBttn") {
    func.displayName = "PlasmicTestBttn";
  } else {
    func.displayName = `PlasmicTestBttn.${nodeName}`;
  }
  return func;
}

export const PlasmicTestBttn = Object.assign(
  // Top-level PlasmicTestBttn renders the root element
  makeNodeComponent("testBttn"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTestBttn
    internalVariantProps: PlasmicTestBttn__VariantProps,
    internalArgProps: PlasmicTestBttn__ArgProps
  }
);

export default PlasmicTestBttn;
/* prettier-ignore-end */
