// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8HMNFKnEv7gJ55SbTqvTiU
// Component: 7BupcZrwoF
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_im_xbeanies.module.css"; // plasmic-import: 8HMNFKnEv7gJ55SbTqvTiU/projectcss
import sty from "./PlasmicUid.module.css"; // plasmic-import: 7BupcZrwoF/css

export const PlasmicUid__VariantProps = new Array();

export const PlasmicUid__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUid__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <div
      data-plasmic-name={"owner0XUid04D1968E100389"}
      data-plasmic-override={overrides.owner0XUid04D1968E100389}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.owner0XUid04D1968E100389
      )}
    >
      {"\nUID: \n04:d1:96:8e:10:03:89\n\n\n"}
    </div>
  );
}

const PlasmicDescendants = {
  owner0XUid04D1968E100389: ["owner0XUid04D1968E100389"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicUid__ArgProps,
          internalVariantPropNames: PlasmicUid__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicUid__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "owner0XUid04D1968E100389") {
    func.displayName = "PlasmicUid";
  } else {
    func.displayName = `PlasmicUid.${nodeName}`;
  }
  return func;
}

export const PlasmicUid = Object.assign(
  // Top-level PlasmicUid renders the root element
  makeNodeComponent("owner0XUid04D1968E100389"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicUid
    internalVariantProps: PlasmicUid__VariantProps,
    internalArgProps: PlasmicUid__ArgProps
  }
);

export default PlasmicUid;
/* prettier-ignore-end */
